<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>제로데이클리닉</title><link rel="stylesheet" href="/css/style.css"></head><body>
<#include "/fragments/header.ftl">
<main>
<section class="hero" aria-label="제로데이클리닉 의료진 소개"><img class="hero-image" src="/images/seohyun-main-hero.png" alt="성형의 기준을 세우다 - 정확한 진단, 안전한 수술, 독보적 결과"></section>
<section class="hero-links" aria-label="주요 서비스 바로가기"><a href="/eye"><span>01</span><strong>성형센터</strong><b>↗</b></a><a href="/reviews"><span>02</span><strong>리얼스토리</strong><b>↗</b></a><a href="/events"><span>03</span><strong>이벤트·혜택</strong><b>↗</b></a></section>
<#if message??><div class="flash success">${message}</div></#if><#if error??><div class="flash error">${error}</div></#if>
<section class="content-band split"><div><div class="home-section-title"><div><p class="eyebrow">Zero Day Signature</p><h2>나에게 꼭 맞는<br>시그니처 프로그램.</h2></div><p>정확한 진단을 바탕으로<br>꼭 필요한 과정만 제안합니다.</p></div><div class="product-grid"><#list procedures as procedure><article class="card product-card"><span class="tag">${procedure.category}</span><h3>${procedure.name}</h3><p>${procedure.summary}</p><strong>${numbers.formatInteger(procedure.price)}원</strong><a class="button button-small" href="/payments/checkout/${procedure.id}">예약 결제</a></article></#list></div></div>
<aside id="quick-consultation" class="quick-form"><p class="eyebrow">Quick Consultation</p><h2>빠른 상담 신청</h2><p class="quick-form-lead">남겨주신 내용을 확인한 뒤 순차적으로 안내해 드립니다.</p><form action="/consultations" method="post"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><input name="name" placeholder="성함" required><input name="phone" placeholder="휴대전화번호" required><select name="area" required><option value="">희망 부위</option><option>눈성형</option><option>코성형</option><option>윤곽/리프팅</option><option>바디성형</option><option>사후관리</option></select><label class="quick-date-label" for="quick-preferred-date">상담 희망 날짜</label><input id="quick-preferred-date" name="preferredDate" type="date" min="${minConsultationDate}" required><select name="preferredContact" required><option>전화 상담</option><option>문자 안내</option><option>카카오톡 안내</option></select><textarea name="message" placeholder="궁금한 내용을 남겨주세요"></textarea><label class="check"><input type="checkbox" name="privacyAgreed" value="true" required> 개인정보 수집 및 이용 동의</label><button class="button" type="submit">상담신청</button></form></aside></section>
<section class="board-band"><div class="content-band columns"><div><div class="section-head"><h2>공지사항</h2><a href="/notices">more</a></div><form action="/notices/search" method="get" class="search-form compact-search"><input type="text" name="keyword" placeholder="공지 제목 검색"><button type="submit" class="button button-small">검색</button></form><ul class="board-list"><#list notices as notice><li><a href="/notices/${notice.id}">${notice.title}</a><time>${temporals.format(notice.createdAt, 'MM-dd')}</time></li></#list></ul></div><div><div class="section-head"><h2>온라인 상담</h2><a href="/qna">more</a></div><ul class="board-list"><#list qnas as post><li><a href="/qna/${post.id}">${post.privatePost?then('비공개 상담글입니다', post.title)}</a><span class="state">${post.answered?then('답변완료', '대기')}</span></li></#list></ul></div></div></section>
<section class="standard-band"><div class="standard-inner"><p class="eyebrow">Our Standard</p><h2>안전을 기본으로,<br>결과로 증명합니다.</h2><div class="standard-grid"><article><b>01</b><strong>1:1 맞춤 진단</strong><span>개인의 특성과 균형을 세심하게 고려합니다.</span></article><article><b>02</b><strong>체계적인 진료</strong><span>상담부터 회복까지 단계별로 관리합니다.</span></article><article><b>03</b><strong>섬세한 사후관리</strong><span>편안한 회복을 위한 케어를 이어갑니다.</span></article></div></div></section>
</main><#include "/fragments/footer.ftl"></body></html>
