[Service]
EnvironmentFile=/etc/clinic/db.env
ExecStart=
ExecStart=/usr/lib/jvm/java-21-openjdk-21.0.12.1.1-1.1.el8_10.x86_64/bin/java -jar /opt/clinic/admin-app.jar --server.port=8080 --server.forward-headers-strategy=native --server.tomcat.use-relative-redirects=true
