[Service]
Environment="APP_UPLOAD_DIR=/opt/clinic/uploads"
Environment="APP_RECORDS_DIR=/opt/clinic/records"
Environment="SERVER_ERROR_WHITELABEL_ENABLED=false"
Environment="SERVER_ERROR_INCLUDE_MESSAGE=never"
Environment="SERVER_ERROR_INCLUDE_STACKTRACE=never"
Environment="SERVER_ERROR_INCLUDE_EXCEPTION=false"
Environment="SERVER_ERROR_INCLUDE_BINDING_ERRORS=never"
