#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""AWS 체크리스트 항목 메타 (SK Shieldus 2024 클라우드 보안가이드, 41항목).

엑셀 양식에서 추출 — 코드/영역/제목/중요도/판단기준/진단경로.
"""

ITEMS = {
    '1.1': {"area": '1. 계정 관리', "title": '사용자 계정 관리', "imp": '상',
        "crit": '양호 - 관리자 권한을 보유한 다수 계정이 존재하지 않고 불필요한 계정이 존재하지 않을 경우\n취약 - 관리자 권한을 보유한 다수 계정이 존재하거나 불필요한 계정이 존재할 경우',
        "path": 'IAM > 사용자 / 사용자 그룹'},
    '1.2': {"area": '1. 계정 관리', "title": 'IAM 사용자 계정 단일화 관리', "imp": '상',
        "crit": '양호 - IAM 사용자 계정을 1인 1계정으로 사용하고 있는 경우\n취약 - IAM 사용자 계정을 1인 1계정으로 사용하고 있지 않은 경우',
        "path": 'IAM > 사용자 목록'},
    '1.3': {"area": '1. 계정 관리', "title": 'IAM 사용자 계정 식별 관리', "imp": '중',
        "crit": '양호 - 사용자 정보(이름, 이메일, 부서 등)가 IAM 사용자 태그에 설정되어 있을 경우\n취약 - 사용자 정보(이름, 이메일, 부서 등)가 IAM 사용자 태그에 설정되어 있지 않을 경우',
        "path": 'IAM > 사용자 > 태그 탭'},
    '1.4': {"area": '1. 계정 관리', "title": 'IAM 그룹 사용자 계정 관리', "imp": '중',
        "crit": '양호 - IAM 그룹에 포함된 사용자 계정 중 불필요한 계정이 존재하지 않을 경우\n취약 - IAM 그룹에 포함된 사용자 계정 중 불필요한 계정이 존재할 경우',
        "path": 'IAM > 사용자 그룹 > 구성원'},
    '1.5': {"area": '1. 계정 관리', "title": 'Key Pair 접근 관리', "imp": '상',
        "crit": '양호 - Key Pair(PEM)를 통해 EC2 인스턴스에 접근할 경우\n취약 - Key Pair(PEM)가 아닌 일반 패스워드로 EC2 인스턴스에 접근할 경우',
        "path": 'EC2 > 키 페어 / 인스턴스 접속 방식'},
    '1.6': {"area": '1. 계정 관리', "title": 'Key Pair 보관 관리', "imp": '상',
        "crit": '양호 - Key Pair(PEM) File의 보관 위치가 쉽게 유추할 수 없는 공간에 보관되어 있을 경우\n취약 - Key Pair(PEM) File의 보관 위치가 다수 접근이 가능한 공용 공간에 보관되어 있을 경우',
        "path": '키 파일 보관 위치 (인터뷰)'},
    '1.7': {"area": '1. 계정 관리', "title": 'Admin Console 관리자 정책 관리', "imp": '중',
        "crit": '양호 - Admin Console 계정을 서비스 용도로 사용하지 않는 경우\n취약 - Admin Console 계정을 서비스 용도로 사용하는 경우',
        "path": 'IAM > 루트 사용자 활동 / CloudTrail'},
    '1.8': {"area": '1. 계정 관리', "title": 'Admin Console 계정 Access Key 활성화 및 사용주기 관리', "imp": '상',
        "crit": '양호 - AWS Admin Console 계정에 Access Key가 존재하지 않고 IAM 사용자 계정에 대한 Access Key 사용주기가 관리되고 있는 경우\n취약 - AWS Admin Console 계정에 Access Key가 존재하거나 IAM 사용자 계정에 대한 Access Key 사용주기가 관리되고 있지 않은 경우',
        "path": 'IAM > 보안 자격 증명 > 액세스 키'},
    '1.9': {"area": '1. 계정 관리', "title": 'MFA (Multi-Factor Authentication) 설정', "imp": '중',
        "crit": '양호 - AWS 계정 및 IAM 사용자 계정 로그인 시 MFA가 활성화 되어 있을 경우\n취약 - AWS 계정 및 IAM 사용자 계정 로그인 시 MFA가 비활성화 되어 있을 경우',
        "path": 'IAM > 사용자 > 보안 자격 증명 > MFA'},
    '1.10': {"area": '1. 계정 관리', "title": 'AWS 계정 패스워드 정책 관리', "imp": '중',
        "crit": '양호 - Admin Console 및 IAM 계정의 패스워드 복잡성 기준 준수 및 암호 만료/재사용 제한을 설정한 경우\n취약 - Admin Console 및 IAM 계정의 패스워드 복잡성 기준 준수 및 암호 만료/재사용 제한을 설정하지 않은 경우',
        "path": 'IAM > 계정 설정 > 암호 정책'},
    '1.11': {"area": '1. 계정 관리', "title": 'EKS 사용자 관리', "imp": '상',
        "crit": '양호 - EKS 리소스 접근을 위한 ConfigMap(RBAC) 내 인가된 사용자만 설정되어 있는 경우\n취약 - EKS 리소스 접근을 위한 ConfigMap(RBAC) 내 인가된 사용자만 설정되어 있지 않은 경우',
        "path": 'EKS > aws-auth ConfigMap'},
    '1.12': {"area": '1. 계정 관리', "title": 'EKS 서비스 어카운트 관리', "imp": '중',
        "crit": '양호 - 네임스페이스 또는 서비스 어카운트 설정 내 automountServiceAccountToken 값이 False로 설정된 경우\n취약 - 네임스페이스 또는 서비스 어카운트 설정 내 automountServiceAccountToken 값이 True로 설정된 경우',
        "path": 'kubectl get sa -o yaml'},
    '1.13': {"area": '1. 계정 관리', "title": 'EKS 불필요한 익명 접근 관리', "imp": '상',
        "crit": '양호 - ClusterRole에 system:anonymous | unauthenticated 그룹이 바인딩되어 있지 않은 경우\n취약 - ClusterRole에 system:anonymous | unauthenticated 그룹이 바인딩되어 있는 경우',
        "path": 'kubectl get clusterrolebinding'},
    '2.1': {"area": '2. 권한 관리', "title": '인스턴스 서비스 정책 관리', "imp": '상',
        "crit": '양호 - 인스턴스 서비스 IAM 사용 권한이 각각 서비스 역할에 맞게 설정되어 있을 경우\n취약 - 인스턴스 서비스 IAM 사용 권한이 각각 서비스 역할에 맞지 않게 설정되어 있을 경우',
        "path": 'IAM > 역할 > EC2 관련 역할 정책'},
    '2.2': {"area": '2. 권한 관리', "title": '네트워크 서비스 정책 관리', "imp": '상',
        "crit": '양호 - 네트워크 서비스 IAM 사용 권한이 각각 서비스 역할에 맞게 설정되어 있을 경우\n취약 - 네트워크 서비스 IAM 사용 권한이 각각 서비스 역할에 맞지 않게 설정되어 있을 경우',
        "path": 'IAM > 역할 > 네트워크 관련 역할 정책'},
    '2.3': {"area": '2. 권한 관리', "title": '기타 서비스 정책 관리', "imp": '상',
        "crit": '양호 - 기타 서비스 IAM 사용 권한이 각각 서비스 역할에 맞게 설정되어 있을 경우\n취약 - 기타 서비스 IAM 사용 권한이 각각 서비스 역할에 맞게 설정되어 있지 않을 경우',
        "path": 'IAM > 역할 / 정책 전체'},
    '3.1': {"area": '3. 가상 리소스 관리', "title": '보안 그룹 인/아웃바운드 ANY 설정 관리', "imp": '상',
        "crit": '양호 - 보안 그룹 내 인/아웃바운드의 포트가 Any로 허용되어 있지 않을 경우\n취약 - 보안 그룹 내 인/아웃바운드의 포트가 Any로 허용되어 있을 경우',
        "path": 'VPC > 보안 그룹 > 인바운드/아웃바운드 규칙'},
    '3.2': {"area": '3. 가상 리소스 관리', "title": '보안 그룹 인/아웃바운드 불필요 정책 관리', "imp": '상',
        "crit": '양호 - 보안 그룹 인/아웃바운드 규칙 내 불필요한 정책(Source, Destination)이 존재하지 않는 경우\n취약 - 보안 그룹 인/아웃바운드 규칙 내 불필요한 정책(Source, Destination)이 존재하는 경우',
        "path": 'VPC > 보안 그룹 > 규칙 상세'},
    '3.3': {"area": '3. 가상 리소스 관리', "title": '네트워크 ACL 인/아웃바운드 트래픽 정책 관리', "imp": '중',
        "crit": '양호 - 네트워크 ACL 내 인/아웃바운드에 대한 모든 트래픽이 허용되어 있지 않을 경우\n취약 - 네트워크 ACL 내 인/아웃바운드에 대한 모든 트래픽이 허용되어 있을 경우',
        "path": 'VPC > 네트워크 ACL'},
    '3.4': {"area": '3. 가상 리소스 관리', "title": '라우팅 테이블 정책 관리', "imp": '중',
        "crit": '양호 - 라우팅 테이블 내 ANY 정책이 설정되어 있지 않고 서비스 타깃 별로 설정되어 있을 경우\n취약 - 라우팅 테이블 내 ANY 정책이 설정되어 있거나 서비스 타깃 별로 설정되어 있지 않을 경우',
        "path": 'VPC > 라우팅 테이블'},
    '3.5': {"area": '3. 가상 리소스 관리', "title": '인터넷 게이트웨이 연결 관리', "imp": '하',
        "crit": '양호 - 인터넷 게이트웨이에 불필요하게 연결된 NAT 게이트웨이가 존재하지 않을 경우\n취약 - 인터넷 게이트웨이에 불필요하게 연결된 NAT 게이트웨이가 존재하는 경우',
        "path": 'VPC > 인터넷 게이트웨이'},
    '3.6': {"area": '3. 가상 리소스 관리', "title": 'NAT 게이트웨이 연결 관리', "imp": '중',
        "crit": '양호 - 외부 통신이 필요한 리소스가 NAT 게이트웨이에 연결되어 있을 경우\n취약 - 목적이 확인되지 않은 리소스가 NAT 게이트웨이에 연결되어 있을 경우',
        "path": 'VPC > NAT 게이트웨이'},
    '3.7': {"area": '3. 가상 리소스 관리', "title": 'S3 버킷/객체 접근 관리', "imp": '중',
        "crit": '양호 - 퍼블릭 액세스 차단이 설정되어 있거나, 퍼블릭 액세스를 허용할 경우 ACL을 버킷 소유자로 제한한 경우\n취약 - 퍼블릭 액세스 차단이 설정되어 있지 않고, ACL이 모든 사람 또는 외부계정 소유자로 설정되어 있는 경우',
        "path": 'S3 > 버킷 > 권한 탭 (퍼블릭 액세스 차단)'},
    '3.8': {"area": '3. 가상 리소스 관리', "title": 'RDS 서브넷 가용 영역 관리', "imp": '중',
        "crit": '양호 - RDS 서브넷 그룹 내 불필요한 가용영역이 존재하지 않는 경우\n취약 - RDS 서브넷 그룹 내 불필요한 가용영역이 존재하는 경우',
        "path": 'RDS > 서브넷 그룹'},
    '3.9': {"area": '3. 가상 리소스 관리', "title": 'EKS Pod 보안 정책 관리', "imp": '상',
        "crit": '양호 - PSS Profile Baseline 및 PSA Audit 이상 설정을 적용해 사용하는 경우\n취약 - PSS 및 PSA 설정을 적용하지 않거나 PSS Profile Privileged 및 PSA warn 설정을 사용하는 경우',
        "path": 'EKS > Pod Security Standards 설정'},
    '3.10': {"area": '3. 가상 리소스 관리', "title": 'ELB(Elastic Load Balancing) 연결 관리', "imp": '중',
        "crit": '양호 - ELB 제어 정책을 준수하고 있는 경우\n취약 - ELB 제어 정책을 준수하고 있지 않는 경우',
        "path": 'EC2 > 로드밸런서'},
    '4.1': {"area": '4. 운영 관리', "title": 'EBS 및 볼륨 암호화 설정', "imp": '중',
        "crit": '양호 - EBS 및 볼륨 리소스에 암호화가 활성화되어 있을 경우\n취약 - EBS 및 볼륨 리소스에 암호화가 비활성화되어 있을 경우',
        "path": 'EC2 > Elastic Block Store > 볼륨 (암호화 열)'},
    '4.2': {"area": '4. 운영 관리', "title": 'RDS 암호화 설정', "imp": '중',
        "crit": '양호 - RDS 데이터베이스 암호화가 활성화되어 있을 경우\n취약 - RDS 데이터베이스 암호화가 비활성화되어 있을 경우',
        "path": 'RDS > 데이터베이스 > 구성 탭'},
    '4.3': {"area": '4. 운영 관리', "title": 'S3 암호화 설정', "imp": '중',
        "crit": '양호 - Amazon S3 키(SSE-S3) 또는 SSE-KMS로 서버 측 암호화가 설정되어 있을 경우\n취약 - Amazon S3 키(SSE-S3) 또는 SSE-KMS로 서버 측 암호화가 설정되어 있지 않을 경우',
        "path": 'S3 > 버킷 > 속성 > 기본 암호화'},
    '4.4': {"area": '4. 운영 관리', "title": '통신구간 암호화 설정', "imp": '중',
        "crit": '양호 - 클라우드 리소스 통신 구간 내 암호화 설정이 되어 있는 경우\n취약 - 클라우드 리소스 통신 구간 내 암호화 설정이 되어 있지 않는 경우',
        "path": 'EC2 > 로드밸런서 > 리스너 및 규칙 / ACM'},
    '4.5': {"area": '4. 운영 관리', "title": 'CloudTrail 암호화 설정', "imp": '중',
        "crit": '양호 - CloudTrail 관련 로그 파일에 SSE-KMS 암호화 설정이 되어 있을 경우\n취약 - CloudTrail 관련 로그 파일에 SSE-KMS 암호화 설정이 되어 있지 않을 경우',
        "path": 'CloudTrail > 추적 > 일반 세부 정보'},
    '4.6': {"area": '4. 운영 관리', "title": 'CloudWatch 암호화 설정', "imp": '중',
        "crit": '양호 - 로그 그룹 생성 시 "KMS key ARN"을 설정하여 사용하고 있는 경우\n취약 - 로그 그룹 생성 시 "KMS key ARN"을 설정하여 사용하고 있지 않는 경우',
        "path": 'CloudWatch > 로그 그룹 > KMS 키 ARN'},
    '4.7': {"area": '4. 운영 관리', "title": 'AWS 사용자 계정 로깅 설정', "imp": '상',
        "crit": '양호 - AWS 사용자 계정(Console, IAM)의 로깅이 설정되어 있는 경우\n취약 - AWS 사용자 계정(Console, IAM)의 로깅이 설정되어 있지 않은 경우',
        "path": 'CloudTrail > 추적 > 관리 이벤트'},
    '4.8': {"area": '4. 운영 관리', "title": '인스턴스 로깅 설정', "imp": '중',
        "crit": '양호 - CloudWatch 로그 스트림으로 보관하고 있는 경우\n취약 - CloudWatch 로그 스트림으로 보관하고 있지 않은 경우',
        "path": 'CloudWatch > 로그 그룹 > 로그 스트림 (EC2)'},
    '4.9': {"area": '4. 운영 관리', "title": 'RDS 로깅 설정', "imp": '중',
        "crit": '양호 - CloudWatch 로그 스트림으로 보관하고 있는 경우\n취약 - CloudWatch 로그 스트림으로 보관하고 있지 않은 경우',
        "path": 'RDS > 구성 > 로그 내보내기 / /aws/rds 로그 그룹'},
    '4.10': {"area": '4. 운영 관리', "title": 'S3 버킷 로깅 설정', "imp": '중',
        "crit": '양호 - 로그를 보관하고 있는 버킷의 "서버 액세스 로깅"이 설정되어 있는 경우\n취약 - 로그를 보관하고 있는 버킷의 "서버 액세스 로깅"이 설정되어 있지 않은 경우',
        "path": 'S3 > 버킷 > 속성 > 서버 액세스 로깅'},
    '4.11': {"area": '4. 운영 관리', "title": 'VPC 플로우 로깅 설정', "imp": '중',
        "crit": '양호 - VPC 플로우 로그 설정이 존재하는 경우\n취약 - VPC 플로우 로그 설정이 존재하지 않을 경우',
        "path": 'VPC > 대상 VPC > 플로우 로그 탭'},
    '4.12': {"area": '4. 운영 관리', "title": '로그 보관 기간 설정', "imp": '중',
        "crit": '양호 - AWS 서비스 로그를 기준(최소 1년 이상)에 맞게 보관하고 있는 경우\n취약 - AWS 서비스 로그를 기준(최소 1년 이상)에 맞게 보관하고 있지 않은 경우',
        "path": 'CloudWatch > 로그 그룹 목록 (보존 기간 열)'},
    '4.13': {"area": '4. 운영 관리', "title": '백업 사용 여부', "imp": '중',
        "crit": '양호 - 클라우드 리소스 백업 정책이 존재하는 경우\n취약 - 클라우드 리소스 백업 정책이 존재하지 않는 경우',
        "path": 'AWS Backup / RDS 자동 백업 / EBS 스냅샷 + 정책 문서'},
    '4.14': {"area": '4. 운영 관리', "title": 'EKS Cluster 제어 플레인 로깅 설정', "imp": '중',
        "crit": '양호 - EKS Cluster 제어 플레인 로깅을 설정하여 유형 별 로그를 기록하고 있는 경우\n취약 - EKS Cluster의 유형 별 로그를 기록하고 있지 않는 경우',
        "path": 'EKS > 클러스터 > Observability'},
    '4.15': {"area": '4. 운영 관리', "title": 'EKS Cluster 암호화 설정', "imp": '중',
        "crit": '양호 - 암호 암호화(Secrets Encryption)가 활성화되어 있는 경우\n취약 - 암호 암호화(Secrets Encryption)가 활성화되어 있지 않는 경우',
        "path": 'EKS > 클러스터 > 개요 > 암호 암호화'},
}
