#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Naver Cloud Platform 체크리스트 항목 메타 (네이버 클라우드 취약점진단 결과보고서 양식 v1.2, 31항목).

항목코드는 워드 양식 그대로(AC/VP/SV/ST/DB/AU/MU) 사용한다.
crit 은 '양호 - ...\\n취약 - ...' 형식(base.Reporter 규약).
"""

ITEMS = {
    # 1. 계정관리
    'AC-01': {"area": '1. 계정관리', "title": '패스워드 복잡성 설정', "imp": '중',
        "crit": '양호 - 영문자·숫자·특수문자를 조합하여 8자 이상으로 패스워드가 설정된 경우\n취약 - 패스워드 조합 규칙을 충족하지 않는 경우',
        "path": 'NCP 콘솔 > 마이페이지 > 로그인 설정 / Sub Account'},
    'AC-02': {"area": '1. 계정관리', "title": '패스워드 최소 길이 설정', "imp": '중',
        "crit": '양호 - 패스워드 최소 길이가 8자 이상으로 설정된 경우\n취약 - 패스워드 최소 길이가 8자 미만인 경우',
        "path": 'NCP 콘솔 > 마이페이지 > 로그인 설정'},
    'AC-03': {"area": '1. 계정관리', "title": '강화된 인증방식 적용', "imp": '중',
        "crit": '양호 - 메인 계정·Sub Account 모두 ID/PW 외 추가 인증수단(인증번호·OTP)을 적용한 경우\n취약 - 2차 인증이 미적용된 계정이 존재하는 경우',
        "path": 'NCP 콘솔 > 마이페이지 > 2단계 인증 / Sub Account'},
    'AC-04': {"area": '1. 계정관리', "title": 'API 인증키 관리', "imp": '상',
        "crit": '양호 - 메인 계정·Sub Account의 Access Key를 주기적으로 관리·교체하는 경우\n취약 - Access Key가 장기간 미교체·방치된 경우',
        "path": 'NCP 콘솔 > 마이페이지 > 인증키 관리 / Sub Account > API Gateway Key'},
    'AC-05': {"area": '1. 계정관리', "title": '계정 권한 부여 방식', "imp": '중',
        "crit": '양호 - Sub Account의 모든 계정이 그룹에 속하여 권한을 부여받은 경우\n취약 - 그룹에 속하지 않은 특수권한 계정이 존재하는 경우',
        "path": 'Sub Account > Group / Member'},
    'AC-06': {"area": '1. 계정관리', "title": '메인 계정 사용 금지', "imp": '상',
        "crit": '양호 - 메인 계정을 사용하지 않고 서브 계정에 적절한 권한을 부여하여 사용하는 경우\n취약 - 메인(루트) 계정을 상시 사용하는 경우',
        "path": 'Sub Account / Cloud Activity Tracer(로그인 이력)'},
    'AC-07': {"area": '1. 계정관리', "title": '불필요한 계정 제거', "imp": '중',
        "crit": '양호 - Sub Account에 불필요·미사용(퇴직·휴직·장기미사용) 계정이 존재하지 않는 경우\n취약 - 불필요·미사용 계정이 존재하는 경우',
        "path": 'Sub Account > Member (최근 로그인 일시)'},
    'AC-08': {"area": '1. 계정관리', "title": '계정 속성 만료 활성화', "imp": '상',
        "crit": '양호 - 미사용 세션 및 비밀번호 만료 기능이 활성화되고 적절한 만료일이 설정된 경우\n취약 - 만료 설정이 비활성화된 경우',
        "path": 'Sub Account > 정책(로그인 정책) / 마이페이지'},
    'AC-09': {"area": '1. 계정관리', "title": '정확한 정책 및 역할 할당', "imp": '상',
        "crit": '양호 - Sub Account 계정에 필요한 정책과 적절한 역할이 할당된 경우\n취약 - 과도하거나 부적절한 정책·역할이 부여된 경우',
        "path": 'Sub Account > Policy / Group'},
    'AC-10': {"area": '1. 계정관리', "title": '통합 계정 관리', "imp": '하',
        "crit": '양호 - Organization으로 거버넌스 정책을 수립하여 계정별 서비스·사용량을 제어하는 경우\n취약 - 다수 계정이 통합 관리 없이 개별 운영되는 경우',
        "path": 'NCP Organization'},
    # 2. 네트워크 보안
    'VP-01': {"area": '2. 네트워크 보안', "title": 'VPC Naming 설정', "imp": '하',
        "crit": '양호 - VPC 이름을 통해 서비스를 식별할 수 있는 경우\n취약 - 식별이 불가능한 이름으로 VPC가 생성된 경우',
        "path": 'VPC > VPC Management'},
    'VP-02': {"area": '2. 네트워크 보안', "title": '서비스 목적에 따른 네트워크 분리', "imp": '중',
        "crit": '양호 - 서비스 사용 목적에 따라 Subnet이 분리된 경우\n취약 - 목적 구분 없이 Subnet이 혼용되는 경우',
        "path": 'VPC > Subnet Management'},
    'VP-03': {"area": '2. 네트워크 보안', "title": 'NACL 관리', "imp": '중',
        "crit": '양호 - 전체 차단 정책을 기본으로 서비스에 필요한 IP·Port만 허용된 경우\n취약 - Network ACL 정책이 없거나 광범위하게 허용된 경우',
        "path": 'VPC > Network ACL'},
    'VP-04': {"area": '2. 네트워크 보안', "title": 'NAT Gateway 관리', "imp": '중',
        "crit": '양호 - 외부 통신이 더 이상 필요 없는 서버가 NAT Gateway 설정에서 제외된 경우\n취약 - 사용 목적이 완료된 서버가 외부 통신 가능 상태로 남아있는 경우',
        "path": 'VPC > NAT Gateway'},
    'VP-05': {"area": '2. 네트워크 보안', "title": '안전한 접속 수단 설정', "imp": '중',
        "crit": '양호 - 정보자산 접속 시 SSL VPN·IPsec VPN·Certificate Manager 등 안전한 접속 수단을 적용한 경우\n취약 - 암호화되지 않은 접속 수단을 사용하는 경우',
        "path": 'VPC > SSL VPN / IPsec VPN, Certificate Manager'},
    # 3. 서버 보안
    'SV-01': {"area": '3. 서버 보안', "title": '서비스 포트 관리', "imp": '상',
        "crit": '양호 - ACG에 서비스에 필요한 IP·Port만 허용된 경우\n취약 - 불필요한 IP·Port(ANY 등)가 허용된 경우',
        "path": 'Server > ACG(Access Control Group) 규칙'},
    'SV-02': {"area": '3. 서버 보안', "title": '서버간 통신 제어', "imp": '중',
        "crit": '양호 - 서버 간 통신이 승인된 정책 범위 내에서만 ACG로 허용된 경우\n취약 - 서버 간 통신이 광범위하게 허용된 경우',
        "path": 'Server > ACG 규칙(Source 가 ACG/서브넷 단위인지)'},
    'SV-03': {"area": '3. 서버 보안', "title": '사용자 접근 통제', "imp": '상',
        "crit": '양호 - 서버 접속 시 인증키를 통해 접속하는 경우\n취약 - ID/Password 직접 입력 방식으로 서버에 접속하는 경우',
        "path": 'Server > 인증키(로그인 키) / 접속 방식(인터뷰)'},
    'SV-04': {"area": '3. 서버 보안', "title": '공인 IP 사용 제한', "imp": '중',
        "crit": '양호 - Private Zone에 위치한 서버에 공인 IP가 할당되지 않은 경우\n취약 - Private Zone 서버에 공인 IP가 할당된 경우',
        "path": 'Server > Public IP / 서버별 공인 IP 할당'},
    'SV-05': {"area": '3. 서버 보안', "title": '불필요한 서버 제거', "imp": '중',
        "crit": '양호 - 사용 목적이 완료된 서버를 정기 검토를 통해 반납 처리하는 경우\n취약 - 불필요한 서버가 미반납 상태로 방치된 경우',
        "path": 'Server > Server (상태/최근 사용)'},
    'SV-06': {"area": '3. 서버 보안', "title": 'OS 취약성 점검', "imp": '중',
        "crit": '양호 - 주기적으로 OS 취약성 점검을 이행하는 경우\n취약 - OS 취약성 점검이 수행되지 않는 경우',
        "path": '보안 점검 이행 내역(인터뷰)'},
    # 4. 스토리지 보안
    'ST-01': {"area": '4. 스토리지 보안', "title": '버킷 공개 설정', "imp": '중',
        "crit": '양호 - 중요정보를 보관한 Object Storage 버킷이 비공개로 설정된 경우\n취약 - 버킷이 외부에 공개로 설정된 경우',
        "path": 'Object Storage > 버킷 > 공개/ACL'},
    'ST-02': {"area": '4. 스토리지 보안', "title": '데이터 수명 주기 관리', "imp": '하',
        "crit": '양호 - 사용 완료 데이터가 수명주기 정책에 따라 Archive Storage 등으로 이관·보관되는 경우\n취약 - 수명주기 정책 없이 데이터가 방치된 경우',
        "path": 'Object Storage > Lifecycle / Archive Storage'},
    'ST-03': {"area": '4. 스토리지 보안', "title": '불필요한 버킷 제거', "imp": '중',
        "crit": '양호 - 사용 목적이 완료된 버킷을 정기 검토를 통해 삭제 처리하는 경우\n취약 - 불필요한 버킷이 방치된 경우',
        "path": 'Object Storage > 버킷 목록(사용 여부)'},
    'ST-04': {"area": '4. 스토리지 보안', "title": 'NAS 접근제어', "imp": '중',
        "crit": '양호 - 사용 중지 서버 또는 공유 대상이 아닌 서버의 NAS 마운트 여부를 주기적으로 점검하는 경우\n취약 - 불필요한 서버가 NAS에 마운트된 경우',
        "path": 'NAS > 볼륨 > 접근제어(ACL)'},
    # 5. DB 보안
    'DB-01': {"area": '5. DB 보안', "title": 'DB 접근통제', "imp": '상',
        "crit": '양호 - DB 접근이 필요한 응용프로그램·서버·사용자를 식별하고 접근통제 정책에 따라 통제하는 경우\n취약 - DB 접근통제 정책이 미흡한 경우',
        "path": 'Cloud DB > 접속 관리(ACG/접근 IP)'},
    'DB-02': {"area": '5. DB 보안', "title": 'DB Backup', "imp": '중',
        "crit": '양호 - 데이터 가용성·무결성 유지를 위해 이중화 구성 및 백업 절차를 마련한 경우\n취약 - 백업·이중화 절차가 마련되지 않은 경우',
        "path": 'Cloud DB > 백업 설정 / 이중화(HA)'},
    # 6. 클라우드 환경 보안 감사
    'AU-01': {"area": '6. 클라우드 환경 보안 감사', "title": '계정 활동 기반 감사', "imp": '중',
        "crit": '양호 - Cloud Activity Tracer로 계정 접근권한 적정성을 정기 검토하는 경우\n취약 - 계정 활동 로그 점검이 이행되지 않는 경우',
        "path": 'Cloud Activity Tracer'},
    'AU-02': {"area": '6. 클라우드 환경 보안 감사', "title": '리소스 기반 감사', "imp": '중',
        "crit": '양호 - Resource Manager로 리소스 생성·변경·삭제 적정성을 정기 검토하는 경우\n취약 - 리소스 변경 이력 점검이 이행되지 않는 경우',
        "path": 'Resource Manager'},
    'AU-03': {"area": '6. 클라우드 환경 보안 감사', "title": '모범 사례 기반 감사', "imp": '중',
        "crit": '양호 - Cloud Advisor 점검항목의 검사결과가 모두 정상인 경우\n취약 - 모범 사례 기반 점검 결과 조치되지 않은 항목이 존재하는 경우',
        "path": 'Cloud Advisor'},
    # 7. 서비스 연속성 확보
    'MU-01': {"area": '7. 서비스 연속성 확보', "title": '멀티존 구성', "imp": '중',
        "crit": '양호 - 중요 서버가 Zone을 통해 이중화되어 있는 경우\n취약 - 중요 서버가 단일 Zone에 구성된 경우',
        "path": 'Server > Zone 분포 / Load Balancer'},
}
