import json
I=json.load(open("inventory.json",encoding="utf-8"))
tag=lambda o: next((t["Value"] for t in (o.get("Tags") or []) if t["Key"]=="Name"),"")
print("VPCs:",[(v["VpcId"],tag(v),v["CidrBlock"],v["IsDefault"]) for v in I["vpcs"]["Vpcs"]])
print("Subnets:",len(I["subnets"]["Subnets"]))
print("RTs:",[(r["RouteTableId"],tag(r)) for r in I["route_tables"]["RouteTables"]])
print("NACLs:",[(n["NetworkAclId"],tag(n),n["IsDefault"]) for n in I["nacls"]["NetworkAcls"]])
print("SGs:",[(g["GroupId"],g["GroupName"]) for g in I["sgs"]["SecurityGroups"]])
print("VPCE:",[(e["VpcEndpointId"],e["ServiceName"].split(".")[-1],e["VpcEndpointType"],e["State"]) for e in I["vpc_endpoints"]["VpcEndpoints"]])
print("EIPs:",[(e.get("AllocationId"),e.get("PublicIp"),e.get("InstanceId"),e.get("NetworkInterfaceId"),tag(e)) for e in I["eips"]["Addresses"]])
print("NAT:",[(n["NatGatewayId"],n["State"],tag(n)) for n in I["nat"]["NatGateways"]])
print("FlowLogs:",[(f["FlowLogId"],f["ResourceId"],f["LogDestinationType"]) for f in I["flow_logs"]["FlowLogs"]])
print("\nInstances:")
for r in I["instances"]["Reservations"]:
    for i in r["Instances"]:
        print("  ",i["InstanceId"],tag(i),i["State"]["Name"],i["InstanceType"],i["ImageId"],i.get("Platform","linux"),i.get("KeyName"),i.get("IamInstanceProfile",{}).get("Arn","").split("/")[-1],i["SubnetId"],[b["Ebs"]["VolumeId"]+":"+b["DeviceName"] for b in i.get("BlockDeviceMappings",[])])
print("\nVolumes:",[(v["VolumeId"],v["Size"],v["State"],v.get("Encrypted"),[x.get("InstanceId") for x in v.get("Attachments",[])],tag(v)) for v in I["volumes"]["Volumes"]])
print("KeyPairs:",[k["KeyName"] for k in I["key_pairs"]["KeyPairs"]])
print("EBS default enc:",I["ebs_default_enc"],I["ebs_default_kms"])
print("\nLBs:",[(l["LoadBalancerName"],l["Scheme"]) for l in I["lbs"]["LoadBalancers"]])
print("TGs:",[t["TargetGroupName"] for t in I["tgs"]["TargetGroups"]])
print("Listeners:",sum(len(v.get("Listeners",[])) for v in I["listeners"].values()),"Rules:",sum(len(v.get("Rules",[])) for v in I["rules"].values()))
print("ACM:",[(c["DomainName"],c.get("Type"),c.get("Status"),c.get("InUse")) for c in I["acm"]["CertificateSummaryList"]])
print("R53 zones:",[(z["Id"],z["Name"],z["Config"].get("PrivateZone")) for z in I["r53_zones"]["HostedZones"]])
for z,v in I["r53_records"].items(): print("  ",z,[(r["Name"],r["Type"]) for r in v.get("ResourceRecordSets",[])])
print("\nBuckets:",[b["Name"] for b in I["buckets"]["Buckets"]])
print("Trails:",[(t["Name"],t.get("S3BucketName"),t.get("KmsKeyId","").split("/")[-1],t.get("CloudWatchLogsLogGroupArn","").split(":")[-2] if t.get("CloudWatchLogsLogGroupArn") else None,t.get("HomeRegion"),t.get("IsMultiRegionTrail")) for t in I["cloudtrail"]["trailList"]])
print("LogGroups:",[g["logGroupName"] for g in I["log_groups"]["logGroups"]])
print("MetricFilters:",[(m["filterName"],m["logGroupName"]) for m in I["metric_filters"].get("metricFilters",[])])
print("Alarms:",[a["AlarmName"] for a in I["alarms"].get("MetricAlarms",[])])
print("SNS:",[t["TopicArn"].split(":")[-1] for t in I["sns_topics"].get("Topics",[])])
print("KMS CMK:",[(k,[x["AliasName"] for x in v["aliases"].get("Aliases",[])],v["rotation"].get("KeyRotationEnabled"),v["meta"]["KeyMetadata"]["KeyState"]) for k,v in I["kms_customer"].items()])
print("Backup plans:",[(p["BackupPlanName"],p["BackupPlanId"]) for p in I["backup_plans"].get("BackupPlansList",[])])
print("Backup vaults:",[v["BackupVaultName"] for v in I["backup_vaults"].get("BackupVaultList",[])])
print("DLM:",[(p["PolicyId"],p.get("Description"),p.get("State")) for p in I["dlm"].get("Policies",[])])
print("GuardDuty:",I["guardduty"],"Config:",[c["name"] for c in I["config_recorders"].get("ConfigurationRecorders",[])])
print("SSM managed:",[(x["InstanceId"],x["PingStatus"],x.get("PlatformName")) for x in I["ssm_instances"].get("InstanceInformationList",[])])
print("SSM params:",[p["Name"] for p in I["ssm_params"].get("Parameters",[])])
print("SSM docs(self):",[d["Name"] for d in I["ssm_docs_self"].get("DocumentIdentifiers",[])])
print("InstanceProfiles:",[(p["InstanceProfileName"],[r["RoleName"] for r in p["Roles"]]) for p in I["iam_instance_profiles"]["InstanceProfiles"]])
print("Local policies:",[p["PolicyName"] for p in I["iam_policies_local"]["Policies"]])
print("WAF:",I["wafv2"].get("WebACLs"),"S3 acct PAB:",I["s3_account_pab"],"Analyzers:",[x["name"] for x in I["access_analyzer"].get("analyzers",[])])
print("EventBridge rules:",[r["Name"] for r in I["eventbridge_rules"].get("Rules",[])])
print("Lambda:",[f["FunctionName"] for f in I["lambda"].get("Functions",[])])
print("Secrets:",[s["Name"] for s in I["secrets"].get("SecretList",[])])
